version: "3.8"

services:
  mysql:
    image: mysql:8.4.6
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: "xampp_mysql"          # no spaces in the DB name
      MYSQL_ROOT_PASSWORD: ""                # empty password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"      # allow login without password
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    restart: always
    environment:
      - NODE_ENV=development
      - DB_NAME=xampp_mysql
      - DB_USER=root
      - DB_PASS=                            # explicitly empty for Sequelize
      - DB_HOST=mysql
      - DB_PORT=3306
    depends_on:
      - mysql
    ports:
      - "3000:3000"

volumes:
  mysql_data:
